n=input('Digite algo:')
print('Qual a classe primitiva?', type(n))
print('Só tem espaços', n.isspace())
print('é  alfanumero?', n.isalnum())
print('é  MINUSCULO?', n.islower())
print('é  decimal?', n.isdecimal())
print('é  indefinido?', n.isidentifier())
print('é  printvel?', n.isprintable())
print('Está capitalizada?', n.istitle())
