print('Progrma para media de notas''\n\n')
nome=input('Digite o primeiro nome do aluno:   ')
n1=int(input('Digite a nota da avaliação 1: '))
n2=int(input('Digite a nota da avaliação 2: '))
n3=int(input('Digite a nota da avaliação 3: '))
print('{} teve media {}'.format(nome, (n1+n2+n3)/3))